// Code generated by entc, DO NOT EDIT.

package site

import (
	"entgo.io/ent"
)

const (
	// Label holds the string label denoting the site type in the database.
	Label = "site"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeRepository holds the string denoting the repository edge name in mutations.
	EdgeRepository = "repository"
	// Table holds the table name of the site in the database.
	Table = "sites"
	// ProjectTable is the table the holds the project relation/edge.
	ProjectTable = "sites"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_sites"
	// RepositoryTable is the table the holds the repository relation/edge.
	RepositoryTable = "sites"
	// RepositoryInverseTable is the table name for the Repository entity.
	// It exists in this package in order to avoid circular dependency with the "repository" package.
	RepositoryInverseTable = "repositories"
	// RepositoryColumn is the table column denoting the repository relation/edge.
	RepositoryColumn = "repository_sites"
)

// Columns holds all SQL columns for site fields.
var Columns = []string{
	FieldID,
	FieldURL,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "sites"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"project_sites",
	"repository_sites",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/fogo-sh/grackdb/ent/runtime"
//
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
)
