// Code generated by entc, DO NOT EDIT.

package project

import (
	"entgo.io/ent"
)

const (
	// Label holds the string label denoting the project type in the database.
	Label = "project"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// EdgeContributors holds the string denoting the contributors edge name in mutations.
	EdgeContributors = "contributors"
	// Table holds the table name of the project in the database.
	Table = "projects"
	// ContributorsTable is the table the holds the contributors relation/edge.
	ContributorsTable = "project_contributors"
	// ContributorsInverseTable is the table name for the ProjectContributor entity.
	// It exists in this package in order to avoid circular dependency with the "projectcontributor" package.
	ContributorsInverseTable = "project_contributors"
	// ContributorsColumn is the table column denoting the contributors relation/edge.
	ContributorsColumn = "project_contributors"
)

// Columns holds all SQL columns for project fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldStartDate,
	FieldEndDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/fogo-sh/grackdb/ent/runtime"
//
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
