// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (da *DiscordAccount) Owner(ctx context.Context) (*User, error) {
	result, err := da.Edges.OwnerOrErr()
	if IsNotLoaded(err) {
		result, err = da.QueryOwner().Only(ctx)
	}
	return result, err
}

func (ga *GithubAccount) Owner(ctx context.Context) (*User, error) {
	result, err := ga.Edges.OwnerOrErr()
	if IsNotLoaded(err) {
		result, err = ga.QueryOwner().Only(ctx)
	}
	return result, err
}

func (ga *GithubAccount) OrganizationMemberships(ctx context.Context) ([]*GithubOrganizationMember, error) {
	result, err := ga.Edges.OrganizationMembershipsOrErr()
	if IsNotLoaded(err) {
		result, err = ga.QueryOrganizationMemberships().All(ctx)
	}
	return result, err
}

func (_go *GithubOrganization) Members(ctx context.Context) ([]*GithubOrganizationMember, error) {
	result, err := _go.Edges.MembersOrErr()
	if IsNotLoaded(err) {
		result, err = _go.QueryMembers().All(ctx)
	}
	return result, err
}

func (gom *GithubOrganizationMember) Organization(ctx context.Context) (*GithubOrganization, error) {
	result, err := gom.Edges.OrganizationOrErr()
	if IsNotLoaded(err) {
		result, err = gom.QueryOrganization().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (gom *GithubOrganizationMember) Account(ctx context.Context) (*GithubAccount, error) {
	result, err := gom.Edges.AccountOrErr()
	if IsNotLoaded(err) {
		result, err = gom.QueryAccount().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) DiscordAccounts(ctx context.Context) ([]*DiscordAccount, error) {
	result, err := u.Edges.DiscordAccountsOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryDiscordAccounts().All(ctx)
	}
	return result, err
}

func (u *User) GithubAccounts(ctx context.Context) ([]*GithubAccount, error) {
	result, err := u.Edges.GithubAccountsOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryGithubAccounts().All(ctx)
	}
	return result, err
}
