// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fogo-sh/grackdb/ent/predicate"
	"github.com/fogo-sh/grackdb/ent/project"
	"github.com/fogo-sh/grackdb/ent/projectcontributor"
	"github.com/fogo-sh/grackdb/ent/user"
)

// ProjectContributorQuery is the builder for querying ProjectContributor entities.
type ProjectContributorQuery struct {
	config
	limit       *int
	offset      *int
	unique      *bool
	order       []OrderFunc
	fields      []string
	predicates  []predicate.ProjectContributor
	withProject *ProjectQuery
	withUser    *UserQuery
	withFKs     bool
	modifiers   []func(*sql.Selector)
	loadTotal   []func(context.Context, []*ProjectContributor) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProjectContributorQuery builder.
func (pcq *ProjectContributorQuery) Where(ps ...predicate.ProjectContributor) *ProjectContributorQuery {
	pcq.predicates = append(pcq.predicates, ps...)
	return pcq
}

// Limit adds a limit step to the query.
func (pcq *ProjectContributorQuery) Limit(limit int) *ProjectContributorQuery {
	pcq.limit = &limit
	return pcq
}

// Offset adds an offset step to the query.
func (pcq *ProjectContributorQuery) Offset(offset int) *ProjectContributorQuery {
	pcq.offset = &offset
	return pcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pcq *ProjectContributorQuery) Unique(unique bool) *ProjectContributorQuery {
	pcq.unique = &unique
	return pcq
}

// Order adds an order step to the query.
func (pcq *ProjectContributorQuery) Order(o ...OrderFunc) *ProjectContributorQuery {
	pcq.order = append(pcq.order, o...)
	return pcq
}

// QueryProject chains the current query on the "project" edge.
func (pcq *ProjectContributorQuery) QueryProject() *ProjectQuery {
	query := &ProjectQuery{config: pcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projectcontributor.Table, projectcontributor.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projectcontributor.ProjectTable, projectcontributor.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(pcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (pcq *ProjectContributorQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: pcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projectcontributor.Table, projectcontributor.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projectcontributor.UserTable, projectcontributor.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(pcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProjectContributor entity from the query.
// Returns a *NotFoundError when no ProjectContributor was found.
func (pcq *ProjectContributorQuery) First(ctx context.Context) (*ProjectContributor, error) {
	nodes, err := pcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{projectcontributor.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pcq *ProjectContributorQuery) FirstX(ctx context.Context) *ProjectContributor {
	node, err := pcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProjectContributor ID from the query.
// Returns a *NotFoundError when no ProjectContributor ID was found.
func (pcq *ProjectContributorQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{projectcontributor.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pcq *ProjectContributorQuery) FirstIDX(ctx context.Context) int {
	id, err := pcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProjectContributor entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProjectContributor entity is found.
// Returns a *NotFoundError when no ProjectContributor entities are found.
func (pcq *ProjectContributorQuery) Only(ctx context.Context) (*ProjectContributor, error) {
	nodes, err := pcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{projectcontributor.Label}
	default:
		return nil, &NotSingularError{projectcontributor.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pcq *ProjectContributorQuery) OnlyX(ctx context.Context) *ProjectContributor {
	node, err := pcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProjectContributor ID in the query.
// Returns a *NotSingularError when more than one ProjectContributor ID is found.
// Returns a *NotFoundError when no entities are found.
func (pcq *ProjectContributorQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{projectcontributor.Label}
	default:
		err = &NotSingularError{projectcontributor.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pcq *ProjectContributorQuery) OnlyIDX(ctx context.Context) int {
	id, err := pcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProjectContributors.
func (pcq *ProjectContributorQuery) All(ctx context.Context) ([]*ProjectContributor, error) {
	if err := pcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pcq *ProjectContributorQuery) AllX(ctx context.Context) []*ProjectContributor {
	nodes, err := pcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProjectContributor IDs.
func (pcq *ProjectContributorQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pcq.Select(projectcontributor.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pcq *ProjectContributorQuery) IDsX(ctx context.Context) []int {
	ids, err := pcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pcq *ProjectContributorQuery) Count(ctx context.Context) (int, error) {
	if err := pcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pcq *ProjectContributorQuery) CountX(ctx context.Context) int {
	count, err := pcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pcq *ProjectContributorQuery) Exist(ctx context.Context) (bool, error) {
	if err := pcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pcq *ProjectContributorQuery) ExistX(ctx context.Context) bool {
	exist, err := pcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProjectContributorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pcq *ProjectContributorQuery) Clone() *ProjectContributorQuery {
	if pcq == nil {
		return nil
	}
	return &ProjectContributorQuery{
		config:      pcq.config,
		limit:       pcq.limit,
		offset:      pcq.offset,
		order:       append([]OrderFunc{}, pcq.order...),
		predicates:  append([]predicate.ProjectContributor{}, pcq.predicates...),
		withProject: pcq.withProject.Clone(),
		withUser:    pcq.withUser.Clone(),
		// clone intermediate query.
		sql:    pcq.sql.Clone(),
		path:   pcq.path,
		unique: pcq.unique,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (pcq *ProjectContributorQuery) WithProject(opts ...func(*ProjectQuery)) *ProjectContributorQuery {
	query := &ProjectQuery{config: pcq.config}
	for _, opt := range opts {
		opt(query)
	}
	pcq.withProject = query
	return pcq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (pcq *ProjectContributorQuery) WithUser(opts ...func(*UserQuery)) *ProjectContributorQuery {
	query := &UserQuery{config: pcq.config}
	for _, opt := range opts {
		opt(query)
	}
	pcq.withUser = query
	return pcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Role projectcontributor.Role `json:"role,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProjectContributor.Query().
//		GroupBy(projectcontributor.FieldRole).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pcq *ProjectContributorQuery) GroupBy(field string, fields ...string) *ProjectContributorGroupBy {
	grbuild := &ProjectContributorGroupBy{config: pcq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pcq.sqlQuery(ctx), nil
	}
	grbuild.label = projectcontributor.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Role projectcontributor.Role `json:"role,omitempty"`
//	}
//
//	client.ProjectContributor.Query().
//		Select(projectcontributor.FieldRole).
//		Scan(ctx, &v)
func (pcq *ProjectContributorQuery) Select(fields ...string) *ProjectContributorSelect {
	pcq.fields = append(pcq.fields, fields...)
	selbuild := &ProjectContributorSelect{ProjectContributorQuery: pcq}
	selbuild.label = projectcontributor.Label
	selbuild.flds, selbuild.scan = &pcq.fields, selbuild.Scan
	return selbuild
}

func (pcq *ProjectContributorQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pcq.fields {
		if !projectcontributor.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pcq.path != nil {
		prev, err := pcq.path(ctx)
		if err != nil {
			return err
		}
		pcq.sql = prev
	}
	if projectcontributor.Policy == nil {
		return errors.New("ent: uninitialized projectcontributor.Policy (forgotten import ent/runtime?)")
	}
	if err := projectcontributor.Policy.EvalQuery(ctx, pcq); err != nil {
		return err
	}
	return nil
}

func (pcq *ProjectContributorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProjectContributor, error) {
	var (
		nodes       = []*ProjectContributor{}
		withFKs     = pcq.withFKs
		_spec       = pcq.querySpec()
		loadedTypes = [2]bool{
			pcq.withProject != nil,
			pcq.withUser != nil,
		}
	)
	if pcq.withProject != nil || pcq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, projectcontributor.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*ProjectContributor).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &ProjectContributor{config: pcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(pcq.modifiers) > 0 {
		_spec.Modifiers = pcq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pcq.withProject; query != nil {
		if err := pcq.loadProject(ctx, query, nodes, nil,
			func(n *ProjectContributor, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := pcq.withUser; query != nil {
		if err := pcq.loadUser(ctx, query, nodes, nil,
			func(n *ProjectContributor, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	for i := range pcq.loadTotal {
		if err := pcq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pcq *ProjectContributorQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*ProjectContributor, init func(*ProjectContributor), assign func(*ProjectContributor, *Project)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProjectContributor)
	for i := range nodes {
		if nodes[i].project_contributors == nil {
			continue
		}
		fk := *nodes[i].project_contributors
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_contributors" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (pcq *ProjectContributorQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ProjectContributor, init func(*ProjectContributor), assign func(*ProjectContributor, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProjectContributor)
	for i := range nodes {
		if nodes[i].user_project_contributions == nil {
			continue
		}
		fk := *nodes[i].user_project_contributions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_project_contributions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pcq *ProjectContributorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pcq.querySpec()
	if len(pcq.modifiers) > 0 {
		_spec.Modifiers = pcq.modifiers
	}
	_spec.Node.Columns = pcq.fields
	if len(pcq.fields) > 0 {
		_spec.Unique = pcq.unique != nil && *pcq.unique
	}
	return sqlgraph.CountNodes(ctx, pcq.driver, _spec)
}

func (pcq *ProjectContributorQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (pcq *ProjectContributorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   projectcontributor.Table,
			Columns: projectcontributor.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: projectcontributor.FieldID,
			},
		},
		From:   pcq.sql,
		Unique: true,
	}
	if unique := pcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectcontributor.FieldID)
		for i := range fields {
			if fields[i] != projectcontributor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pcq *ProjectContributorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pcq.driver.Dialect())
	t1 := builder.Table(projectcontributor.Table)
	columns := pcq.fields
	if len(columns) == 0 {
		columns = projectcontributor.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pcq.sql != nil {
		selector = pcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pcq.unique != nil && *pcq.unique {
		selector.Distinct()
	}
	for _, p := range pcq.predicates {
		p(selector)
	}
	for _, p := range pcq.order {
		p(selector)
	}
	if offset := pcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProjectContributorGroupBy is the group-by builder for ProjectContributor entities.
type ProjectContributorGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pcgb *ProjectContributorGroupBy) Aggregate(fns ...AggregateFunc) *ProjectContributorGroupBy {
	pcgb.fns = append(pcgb.fns, fns...)
	return pcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pcgb *ProjectContributorGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pcgb.path(ctx)
	if err != nil {
		return err
	}
	pcgb.sql = query
	return pcgb.sqlScan(ctx, v)
}

func (pcgb *ProjectContributorGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pcgb.fields {
		if !projectcontributor.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pcgb *ProjectContributorGroupBy) sqlQuery() *sql.Selector {
	selector := pcgb.sql.Select()
	aggregation := make([]string, 0, len(pcgb.fns))
	for _, fn := range pcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pcgb.fields)+len(pcgb.fns))
		for _, f := range pcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pcgb.fields...)...)
}

// ProjectContributorSelect is the builder for selecting fields of ProjectContributor entities.
type ProjectContributorSelect struct {
	*ProjectContributorQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pcs *ProjectContributorSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pcs.prepareQuery(ctx); err != nil {
		return err
	}
	pcs.sql = pcs.ProjectContributorQuery.sqlQuery(ctx)
	return pcs.sqlScan(ctx, v)
}

func (pcs *ProjectContributorSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pcs.sql.Query()
	if err := pcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
