// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DiscordAccount is the predicate function for discordaccount builders.
type DiscordAccount func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
